spring.application.name=yourstube-be

spring.datasource.url=jdbc:postgresql://localhost:5432/yourstube
spring.datasource.username=yourstube
spring.datasource.password=yourstube

spring.jpa.hibernate.ddl-auto=update
