CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    youtube_channel_id VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    thumbnail_url TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    youtube_video_id VARCHAR(20) NOT NULL UNIQUE,
    channel_id BIGINT NOT NULL,

    title VARCHAR(500) NOT NULL,
    description TEXT,
    thumbnail_url TEXT,
    duration_seconds BIGINT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_video_channel
        FOREIGN KEY (channel_id)
        REFERENCES channels(id)
);


CREATE TABLE playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,

    title VARCHAR(255) NOT NULL,
    description TEXT,

    type VARCHAR(30) NOT NULL,

    youtube_playlist_id VARCHAR(100),
    youtube_playlist_url TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_playlist_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(id),

    CONSTRAINT fk_playlist_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(id)
);


CREATE TABLE playlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    playlist_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,

    position INTEGER NOT NULL,

    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_playlist_item_playlist
        FOREIGN KEY (playlist_id)
        REFERENCES playlists(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_playlist_item_video
        FOREIGN KEY (video_id)
        REFERENCES videos(id),

    CONSTRAINT uk_playlist_video
        UNIQUE (playlist_id, video_id),

    CONSTRAINT uk_playlist_position
        UNIQUE (playlist_id, position)
);

